# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: ♬ Phantom Blog
subtitle: '梦幻空花 ~ 何劳把捉'
description: '↑↑↓↓←←→→abab<br/>提供机制而不是策略!!!'
keywords: music,development,software,blog,hacker,cracker,reverse,network,音乐,软件开发,逆向
author: huzhiqin
language: zh-CN
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://phantom27.xyz
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: true
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: '    '
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

math:
  engine: 'mathjax'
  mathjax:
    enable: true
  katex:
    # css: /lib/katex/katex.min.css
    css: //cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css

mathjax:
  tags: all # or 'ams' or 'all'
  single_dollars: true # enable single dollar signs as in-line math delimiters
  cjk_width: 0.9 # relative CJK char width
  normal_width: 0.6 # relative normal (monospace) width
  append_css: true # add CSS to every page
  every_page: false # if true, every page will be rendered by mathjax regardless the `mathjax` setting in Front-matter of each article

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 4
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 4
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

excerpt:
  depth: 10
  excerpt_excludes: []
  more_excludes: []
  hideWholePostExcerpts: true

bookmark:
  enable: true
  save: auto

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next
theme_config:
  favicon:
    small: /images/favicon-16x16.ico
    medium: /images/favicon-32x32.ico
    apple_touch_icon: /images/apple-touch-icon.png

plugins:
  - hexo-footnote

reading_count:
  enable: true
  # increase_url: https://api.phantom27.xyz/blog/increase_post_pv
  # fetch_url: https://api.phantom27.xyz/blog/fetch_post_pv
  increase_url: https://api.phantom27.xyz/blog/increase_post_pv
  fetch_url: https://api.phantom27.xyz/blog/fetch_post_pv
  # axios: /lib/axios/axios.min.js
  axios: //cdn.jsdelivr.net/npm/axios@1.7.7/dist/axios.min.js

# lazyload:
#   enable: true
#   onlypost: false # optional
#   loadingImg: # optional eg ./images/loading.gif
#   isSPA: false # optional
#   preloadRatio: 3 # optional, default is 1

html_minifier:
  exclude:
  collapseBooleanAttributes: true
  collapseWhitespace: true
  # Ignore '<!-- more -->' https://hexo.io/docs/tag-plugins#Post-Excerpt
  ignoreCustomComments: [ !!js/regexp /^\s*more/]
  removeComments: true
  removeEmptyAttributes: true
  removeScriptTypeAttributes: true
  removeStyleLinkTypeAttributes: true
  minifyJS: true
  minifyCSS: true

footnote:
  location_target_class: location-target

# Word Count
symbols_count_time:
  symbols: true
  time: true
  total_symbols: false
  total_time: false
  exclude_codeblock: true

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: repo@phantom27.tpddns.cn:/repo/blog-public.git
  branch: public

since: 2022
