name: Publish Github Page

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  TZ: Asia/Shanghai

jobs:
  hook:
    runs-on: ubuntu-20.04
    steps:
      - name: Report Update Blog
        env:
          PAGE_UPDATE_TOKEN: ${{ secrets.PAGE_UPDATE_TOKEN }}
        run: curl -L https://api.phantom27.xyz/cgi/blog/update?token=$PAGE_UPDATE_TOKEN

  build:
    needs: hook
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      
      - name: Pandoc
        uses: docker://pandoc/core:2.9

      - name: Config environment
        env:
          PAGE_PUBLISH_TOKEN: ${{ secrets.PAGE_PUBLISH_TOKEN }}
          PHANTOM_REPO_TOKEN: ${{ secrets.PHANTOM_REPO_TOKEN }}
          PUBLISH_NAME: 'bot'
          PUBLISH_MAIL: '604916833@qq.com'
        run: |
          echo "${{ secrets.PAGE_PUBLISH_TOKEN }}" > ~/.ssh/deploy_token
          chmod 700 ~/.ssh/deploy_token
          ssh-keyscan -H phantom27.tpddns.cn >> ~/.ssh/known_hosts
          git config --global user.name $PUBLISH_NAME
          git config --global user.email $PUBLISH_MAIL
          sed -i "s/PAGE_PUBLISH_TOKEN/$PAGE_PUBLISH_TOKEN/g" ./_config.yml

      - name: Install dependencies
        run: |
          sudo apt-get install pandoc -y
          npm install hexo-cli -g
          npm install

      - name: Generate hexo static page
        run: |
          hexo clean
          hexo generate

      - name: Deploy hexo static page
        run: GIT_SSH_COMMAND='ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_token' hexo deploy

#      - name: Upload Pages artifact
#        uses: actions/upload-pages-artifact@v3
#        with:
#          path: ./public

      # - name: Deploy hexo static page
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     token: ${{ secrets.PAGE_PUBLISH_TOKEN }}
      #     branch: gh-pages
      #     folder: ./public

#  deploy:
#    needs: build
#    permissions:
#      pages: write
#      id-token: write
#    environment:
#      name: github-pages
#      url: ${{ steps.deployment.outputs.page_url }}
#    runs-on: ubuntu-20.04
#    steps:
#      - name: Deploy to GitHub Pages
#        id: deployment
#        uses: actions/deploy-pages@v4
