name: Publish Github Page

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: Config environment
        env:
          PAGE_PUBLISH_TOKEN: ${{ secrets.PAGE_PUBLISH_TOKEN }}
          PUBLISH_NAME: 'bot'
          PUBLISH_MAIL: '604916833@qq.com'
        run: |
          git config --global user.name $PUBLISH_NAME
          git config --global user.email $PUBLISH_MAIL

      - name: Install dependencies
        run: |
          npm install hexo-cli -g
          npm install

      - name: Generate hexo static page
        run: |
          hexo clean
          hexo generate

      - name: Deploy hexo static page
        run: hexo deploy