name: Publish Github Page

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-lastest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: {{matrix.node-version}}
      - npm install
        env:
          CI: true
      run: hexo generate